### ISSUE TITLE
Can't use the deploy delta

### ISSUE THREAD

**Issue by uxkjaer** [mikezaschka/cds-dbm#220]
I've followed the [blog](https://blogs.sap.com/2020/11/16/getting-started-with-cap-on-postgresql-node.js/) to create my own schema and steps. However when I'm trying to deploy my csv file it fails. t seems like it isn't picking up the custom builder for pg and instead using the default.
 Here is the error. Config is below
## log
TypeError: Cannot read properties of undefined (reading 'regularRegex')
    at smartId (/home/jakob/git/fueldb/fueldb/node_modules/cds-pg/node_modules/@sap/cds-compiler/lib/sql-identifier.js:66:9)
    at _smartId (/home/jakob/git/fueldb/fueldb/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/common/utils/quotingStyles.js:19:23)
    at PGReferenceBuilder.plain [as _quoteElement] (/home/jakob/git/fueldb/fueldb/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/common/utils/quotingStyles.js:46:12)
    at /home/jakob/git/fueldb/fueldb/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/sql-builder/ReferenceBuilder.js:106:49
    at Array.map (<anonymous>)
    at PGReferenceBuilder._parseReference (/home/jakob/git/fueldb/fueldb/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/sql-builder/ReferenceBuilder.js:106:34)
    at PGReferenceBuilder.build (/home/jakob/git/fueldb/fueldb/node_modules/cds-pg/lib/pg/sql-builder/ReferenceBuilder.js:44:52)
    at PGSelectBuilder._buildRefElement (/home/jakob/git/fueldb/fueldb/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/sql-builder/SelectBuilder.js:272:68)
    at PGSelectBuilder._buildElement (/home/jakob/git/fueldb/fueldb/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/sql-builder/SelectBuilder.js:246:18)
    at /home/jakob/git/fueldb/fueldb/node_modules/cds-pg/node_modules/@sap/cds/libx/_runtime/db/sql-builder/SelectBuilder.js:311:56

## Package.json config
  "cds": {
    "build": {
      "tasks": [
        {
          "use": "node-cf",
          "for": "node-cf",
          "src": "srv"
        },
        {
          "use": "postgres-cf",
          "for": "postgres-cf",
          "src": "db",
          "options": {
            "deployCmd": "npx cds-dbm deploy --load-via delta --auto-undeploy"
          }
        }
      ]
    },
    "requires": {
      "db": {
        "kind": "database"
      },
      "database": {
        "impl": "cds-pg",
        "model": [
          "srv"
        ],
        "credentials": {
          "host": "localhost",
          "port": 5432,
          "database": "postgres",
          "user": "postgres",
          "password": "postgres"
        }
      }
    },
    "migrations": {
      "db": {
        "schema": {
          "default": "public",
          "clone": "_cdsdbm_clone",
          "reference": "_cdsdbm_ref"
        },
        "deploy": {
          "tmpFile": "tmp/_autodeploy.json",
          "undeployFile": "db/undeploy.json"
        }
      }
    }
  }
}

## Schema: 
using { cuid } from '@sap/cds/common';
namespace db;

entity FuelPrices: cuid {
  SiteId: Integer;
  Site_Name: String;
  Site_Brand: String;
  Site_Address: String;
  Site_Suburb: String;
  Site_State: Association to one State;
  Site_Post_Code: Association to one PostCode;
  Site_Latitude: String;
  Site_Longitude: String;
  Fuel_Type: String;
  Price: Integer;
  TransactionDateUtc: String;
}

entity State: cuid {
    name: String;
    FuelPrices: Association to many FuelPrices on FuelPrices.Site_State = $self
}

entity PostCode: cuid {
    name: String;
        FuelPrices: Association to many FuelPrices on FuelPrices.Site_Post_Code = $self

}

**Comment by uxkjaer** [comment]
Finally figured it out. I had to set the dialect as well in the package.json file
 "db": {
        "kind": "database",
        "dialect": "plain"

      },
