### ISSUE TITLE
CDS-DBM Deploy Error: TypeError: Cannot read properties of undefined (reading 'definitions')

### ISSUE THREAD

**Issue by dus2001** [mikezaschka/cds-dbm#307]
Hello Gregor,

I really appreciate what you have done with the pg integration into CDS. I have been trying to understand and learn this. What I am posting here is two fold (1) an issue I am facing (2) help I would like so I can start troubleshooting CDS-DBM on my own.

(1) I built a simple application using the risks/mitigations tutorial from SAP. It runs fine locally on my mac. But when I deploy to BTP that fails. I am using a standard pg-database and not trial. Here is the error I get.
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/4270173/222824866-492d5e1a-7982-40e9-a4e3-2e59183320a7.png">

(2) I am trying to figure out a way to debug this. full disclosure, I am a newbie to nodejs. But I do have many years of development experience so I think I am able to follow what is happening here.
How do I debug cds-dbm? (deploy). either locally or on BTP? Are you able to point me to some help for that please?
the deployer itself stays in stopped state. 
Does it have to do with the serverjs? Do I change the start script to run the server.js and then ssh into the app? 

Thank you
Durga

**Comment by dus2001** [comment]
Also, I started off with the original blog by Mike and realized it is outdated. Trying to add your updates in beer shop into the original. My problem is that beershop is too complex. I want to start from something very simple and clean slate and introduce one item at a time so I am learning the concepts gradually. Beershop is firehose. Once I can implement a "simplem application" I can move on to understanding beershop.

And my intention is to build a productive application and I prefer that to have only what is needed.

**Comment by dus2001** [comment]
I started from scratch borrowing the definitions from @gregorwolf pg-beershop. And I am now deploying to my local postgres on docker. My deploy --create-db goes through without problem. I also see the definitions of the tables in the postgres datbaase. But I get an error when I try to load the data using :
`npm run deploy:pg:data:full`
Here is the error:

TypeError: Cannot read properties of undefined (reading 'definitions')
    at /Users/dus2001/git/testpgdb/node_modules/cds-pg/lib/pg/execute.js:88:60
    at Array.map (<anonymous>)
    at executeInsertCQN (/Users/dus2001/git/testpgdb/node_modules/cds-pg/lib/pg/execute.js:88:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports [as _CREATE] (/Users/dus2001/git/testpgdb/node_modules/@sap/cds/libx/_runtime/db/generic/create.js:18:21)
    at async next (/Users/dus2001/git/testpgdb/node_modules/@sap/cds/lib/srv/srv-dispatch.js:75:17)
    at async PostgresDatabase.handle (/Users/dus2001/git/testpgdb/node_modules/@sap/cds/lib/srv/srv-dispatch.js:73:10)
    at async DataLoader._performFullUpdate (/Users/dus2001/git/testpgdb/node_modules/cds-dbm/dist/DataLoader.js:111:13)
    at async DataLoader.loadFrom (/Users/dus2001/git/testpgdb/node_modules/cds-dbm/dist/DataLoader.js:82:17)
    at async PostgresAdapter.load (/Users/dus2001/git/testpgdb/node_modules/cds-dbm/dist/adapter/BaseAdapter.js:66:9) {
  numericSeverity: 4
}

It seems the deploy module is not finding the database name. And it is using the "db" by default. I am stuck. Please help

Here is my default-env.json:

{
    "VCAP_SERVICES": {
      "postgres": [
        {
          "name": "pg-database",
          "label": "postgres",
          "tags": ["plain", "db", "relational", "database"],
          "credentials": {
            "host": "localhost",
            "port": "5432",
            "database": "testpgdb",
            "user": "postgres",
            "password": "postgres"
          }
        }
      ]
    }
  }

**Comment by dus2001** [comment]
This is resolved. The problem was that I was copying the db-deployer-apt from the beershop repository. I deleted the library and redeployed. Now the deploy works good.
