### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'definitions')

### ISSUE THREAD

**Issue by muellerj93** [mikezaschka/cds-dbm#308]
Hi,

I'm facing the same issue as [307](https://github.com/mikezaschka/cds-dbm/issues/307).
The difference is, that I didn't copy the `db-deployer-apt` from the `beershop` application.

The logs after the deployment are:

```
2023-03-06T17:07:16.41+0100 [APP/TASK/deploy_to_postgresql/0] OUT [cds-dbm] - starting delta database deployment of service db
2023-03-06T17:07:37.04+0100 [APP/TASK/deploy_to_postgresql/0] OUT [cds-dbm] - delta successfully deployed to the database
2023-03-06T17:07:37.28+0100 [APP/TASK/deploy_to_postgresql/0] OUT [cds-dbm] - loading data from /home/vcap/app/data/schwarz.sci.monitoring-MetricTypesList.csv
2023-03-06T17:07:37.32+0100 [APP/TASK/deploy_to_postgresql/0] ERR cds-dbm deploy [services]
2023-03-06T17:07:37.32+0100 [APP/TASK/deploy_to_postgresql/0] ERR Dynamically identifies changes in your cds data model and deploys them to the
2023-03-06T17:07:37.32+0100 [APP/TASK/deploy_to_postgresql/0] ERR database
2023-03-06T17:07:37.32+0100 [APP/TASK/deploy_to_postgresql/0] ERR Options:
2023-03-06T17:07:37.32+0100 [APP/TASK/deploy_to_postgresql/0] ERR --help           Show help                                       [boolean]
2023-03-06T17:07:37.32+0100 [APP/TASK/deploy_to_postgresql/0] ERR --version        Show version number                             [boolean]
2023-03-06T17:07:37.32+0100 [APP/TASK/deploy_to_postgresql/0] ERR -s, --service                                                [default: ["db"]]
2023-03-06T17:07:37.32+0100 [APP/TASK/deploy_to_postgresql/0] ERR -a, --auto-undeploy
2023-03-06T17:07:37.32+0100 [APP/TASK/deploy_to_postgresql/0] ERR -d, --dry
2023-03-06T17:07:37.32+0100 [APP/TASK/deploy_to_postgresql/0] ERR -l, --load-via
2023-03-06T17:07:37.32+0100 [APP/TASK/deploy_to_postgresql/0] ERR -c, --create-db
2023-03-06T17:07:37.33+0100 [APP/TASK/deploy_to_postgresql/0] ERR TypeError: Cannot read properties of undefined (reading 'definitions')
2023-03-06T17:07:37.33+0100 [APP/TASK/deploy_to_postgresql/0] ERR at PGSelectBuilder._columns (/home/vcap/deps/1/node_modules/cds-pg/lib/pg/sql-builder/SelectBuilder.js:84:32)
2023-03-06T17:07:37.33+0100 [APP/TASK/deploy_to_postgresql/0] ERR at PGSelectBuilder.build (/home/vcap/deps/1/node_modules/@sap/cds/libx/_runtime/db/sql-builder/SelectBuilder.js:81:10)
2023-03-06T17:07:37.33+0100 [APP/TASK/deploy_to_postgresql/0] ERR at build (/home/vcap/deps/1/node_modules/@sap/cds/libx/_runtime/db/sql-builder/sqlFactory.js:65:43)
2023-03-06T17:07:37.33+0100 [APP/TASK/deploy_to_postgresql/0] ERR at build (/home/vcap/deps/1/node_modules/@sap/cds/libx/_runtime/db/sql-builder/sqlFactory.js:74:12)
2023-03-06T17:07:37.33+0100 [APP/TASK/deploy_to_postgresql/0] ERR at _cqnToSQL (/home/vcap/deps/1/node_modules/cds-pg/lib/pg/execute.js:148:5)
2023-03-06T17:07:37.33+0100 [APP/TASK/deploy_to_postgresql/0] ERR at executeSelectCQN (/home/vcap/deps/1/node_modules/cds-pg/lib/pg/execute.js:51:34)
2023-03-06T17:07:37.33+0100 [APP/TASK/deploy_to_postgresql/0] ERR at PostgresDatabase._read (/home/vcap/deps/1/node_modules/@sap/cds/libx/_runtime/db/query/read.js:74:10)
2023-03-06T17:07:37.33+0100 [APP/TASK/deploy_to_postgresql/0] ERR at module.exports [as _READ] (/home/vcap/deps/1/node_modules/@sap/cds/libx/_runtime/db/generic/read.js:15:15)
2023-03-06T17:07:37.33+0100 [APP/TASK/deploy_to_postgresql/0] ERR at next (/home/vcap/deps/1/node_modules/@sap/cds/lib/srv/srv-dispatch.js:75:36)
2023-03-06T17:07:37.33+0100 [APP/TASK/deploy_to_postgresql/0] ERR at PostgresDatabase.handle (/home/vcap/deps/1/node_modules/@sap/cds/lib/srv/srv-dispatch.js:79:6)
2023-03-06T17:07:37.34+0100 [APP/TASK/deploy_to_postgresql/0] ERR npm notice
2023-03-06T17:07:37.34+0100 [APP/TASK/deploy_to_postgresql/0] ERR npm notice New major version of npm available! 8.19.3 -> 9.6.0
2023-03-06T17:07:37.34+0100 [APP/TASK/deploy_to_postgresql/0] ERR npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.0>
2023-03-06T17:07:37.34+0100 [APP/TASK/deploy_to_postgresql/0] ERR npm notice Run `npm install -g npm@9.6.0` to update!
2023-03-06T17:07:37.34+0100 [APP/TASK/deploy_to_postgresql/0] ERR npm notice
2023-03-06T17:07:37.35+0100 [APP/TASK/deploy_to_postgresql/0] OUT Exit status 1
```

I've already tried to deploy the same schema to a locally installed postgres database (via docker), by issuing the same command that the deploy task runs:

`npx cds-dbm deploy --load-via delta --auto-undeploy`

This doesn't produce any error on my machine, and it doesn't even call the functions that are mentioned in the callstack above.

Unfortunately I have no idea how to solve this error or what to check, as it looks to me that the deployment itself is working (see success messages in the logs above).

Can someone help me?

Thanks, Regards

**Comment by frankmeertens** [comment]
I was experiencing the same issue. When you look at the `package.json` of the `pg-beershop`, you can see the `cds-pg` version is set to `0.1.33` and the `cds-dbm` version is set to `^0.0.36`. 
When I run with those parameters, the problem is not occurring. 

Quick debug shows that the `cds.model` is not loaded and errors out when calling for instance the `INSERT` statement during the `cds-dbm` data loader. With the package version combination stated above, the problem should not occur.

Hope this helps?

**Comment by muellerj93** [comment]
Hi,

thank you very much, this solved my issue.
I additionally had to downgrade from @sap/cds v6.5.0 to 5.9.8.

But what's still strange to me is, is that the deployment works on a local postgre database, but not on one in the BTP.

Best regards

**Comment by frankmeertens** [comment]
The deployment to CF worked for me. Also check #309. Tried a local workaround that seems to work. It seemed to work for me using @sap/cds version 6.6.1 and the latest cds-pg and cds-dbm versions.
