### ISSUE TITLE
Cannot read properties of undefined (reading 'regularRegex')

### ISSUE THREAD

**Issue by pankajvalecha** [mikezaschka/cds-dbm#309]
Hi Experts,

I am trying to use cds dbm deploy command : **npx cds-dbm deploy --load-via full** 
with latest version of sap-cds, cds-dbm, cds-pg respectively  ( as per their github homepage )
"@sap/cds": "6.6.0",
"cds-pg": "0.1.35",
"cds-dbm": "0.1.2"

but it is throwing error while loading csv files with  regularRegex error whereas previous versions are working properly but have vulnerability issues which the newer version got fixed with them.

**Logs :** 
Cannot read properties of undefined (reading 'regularRegex')
    at smartId (C:\Users\~\srv\node_modules\@sap\cds-compiler\lib\sql-identifier.js:79:9)
    at _smartId (C:\Users\~\srv\node_modules\@sap\cds\libx\_runtime\common\utils\quotingStyles.js:9:23)
    at InsertBuilder.plain [as _quoteElement] (C:\Users\~\srv\node_modules\@sap\cds\libx\_runtime\common\utils\quotingStyles.js:23:12)
at InsertBuilder._into (C:\Users\PankajValecha\TJCCode\COREEXCH\core-exchange\coreexch-srv\node_modules\@sap\cds\libx\_runtime\db\sql-builder\InsertBuilder.js:132:37)
    at InsertBuilder.build (C:\Users\PankajValecha\TJCCode\COREEXCH\core-exchange\coreexch-srv\node_modules\@sap\cds\libx\_runtime\db\sql-builder\InsertBuilder.js:72:29)
    at build (C:\Users\~\srv\node_modules\@sap\cds\libx\_runtime\db\sql-builder\sqlFactory.js:65:43)
    at build (C:\Users\~\srv\node_modules\@sap\cds\libx\_runtime\db\sql-builder\sqlFactory.js:78:12)
    at _cqnToSQL (C:\Users\~\srv\node_modules\cds-pg\lib\pg\execute.js:148:5)
    at executeInsertCQN (C:\User\~\srv\node_modules\cds-pg\lib\pg\execute.js:72:32)
    at PostgresDatabase._insert (C:\Users\~\srv\node_modules\@sap\cds\libx\_runtime\db\query\insert.js:18:10) {
  numericSeverity: 4
}

Can someone help me here?

Thanks, Regards
Pankaj Valecha

**Comment by frankmeertens** [comment]
From what I can tell, the problem is related to the load. Try deployment without the `--load-via full` option. This should work with the releases you show.

The problem seems to be with the `cds-pgm` DataLoader class calling the INSERT statement without the cds models that have been loaded. 

I tried to add a `const test = await cds.serve('all') ` to the '`loadFrom' method and that seems to resolve the issue. Not sure whether someone is working on this problem at the moment? Will check the other threads.

**Comment by mikezaschka** [comment]
@frankmeertens: Thank you for the valuable input. It is indeed required to call `cds.serve` now before accessing CQL. I released a new version of cds-dbm that fixes this issue (`cds-dbm@0.1.3`).

I also update my example repo to fully support the latest versions of all libraries: https://github.com/mikezaschka/cap-devtoberfest

**Comment by frankmeertens** [comment]
Thanks for the quick turnaround, Mike! I pulled in the new version and is working for me.
